# -*- coding: utf-8 -*-
"""Copy of Thesis code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3yJ05yeK_yILU24PruKxadhrqjzzI3G

Install Libraries
"""

!pip install sentence-transformers
!pip install faiss-cpu
!pip install rank-bm25
!pip install pandas
!pip install tqdm
!pip install transformers

!wget https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/All_Beauty.jsonl

import pandas as pd
import json

data = []

with open("All_Beauty.jsonl") as f:
    for line in f:
        data.append(json.loads(line))

df = pd.DataFrame(data)

print("Dataset size:", len(df))
df.head()

documents = df['text'].dropna().tolist()

print("Total documents:", len(documents))
print(documents[0])

documents = documents[:5000]

from rank_bm25 import BM25Okapi

tokenized_docs = [doc.split() for doc in documents]

bm25 = BM25Okapi(tokenized_docs)

query = "good moisturizer for dry skin"

tokenized_query = query.split()

scores = bm25.get_scores(tokenized_query)

import numpy as np

top_n = np.argsort(scores)[::-1][:5]

print("BM25 Results:\n")

for i in top_n:
    print(documents[i])
    print("-----")

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(documents, show_progress_bar=True)

import faiss
import numpy as np

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(np.array(embeddings))

print("FAISS index size:", index.ntotal)

query = "good moisturizer for dry skin"

query_embedding = model.encode([query])

k = 5

distances, indices = index.search(np.array(query_embedding), k)

print("FAISS Results:\n")

for idx in indices[0]:
    print(documents[idx])
    print("-----")

queries = [
    "moisturizer for dry skin",
    "long lasting lipstick",
    "face cleanser for sensitive skin",
    "anti aging cream",
]

for query in queries:

    tokenized_query = query.split()

    scores = bm25.get_scores(tokenized_query)

    top_bm25 = np.argsort(scores)[::-1][:3]

    query_embedding = model.encode([query])

    distances, indices = index.search(np.array(query_embedding), 3)

    print("\nQuery:", query)

    print("\nBM25 results:")
    for i in top_bm25:
        print("-", documents[i][:120])

    print("\nFAISS results:")
    for i in indices[0]:
        print("-", documents[i][:120])

import time

query = "moisturizer for dry skin"

start = time.time()
bm25.get_scores(query.split())
bm25_time = time.time() - start

start = time.time()
model.encode([query])
index.search(np.array(query_embedding), 5)
faiss_time = time.time() - start

print("BM25 Time:", bm25_time)
print("FAISS Time:", faiss_time)

import matplotlib.pyplot as plt

methods = ['BM25', 'FAISS']
times = [bm25_time, faiss_time]

plt.bar(methods, times)
plt.title("Retrieval Latency Comparison")
plt.ylabel("Time (seconds)")
plt.show()

def generate_answer(query, docs):
    context = " ".join(docs)
    answer = f"Based on retrieved reviews: {context[:500]}"
    return answer

import json
import numpy as np
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
import faiss
from transformers import pipeline

def load_reviews(file_path, limit=5000):
    documents = []

    with open(file_path, "r") as f:
        for i, line in enumerate(f):
            if i >= limit:
                break
            data = json.loads(line)
            if "reviewText" in data:
                documents.append(data["reviewText"])

    return documents

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

doc_embeddings = embedding_model.encode(documents)

dimension = doc_embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(np.array(doc_embeddings))

def retrieve_bm25(query, k=5):

    tokenized_query = query.split()

    scores = bm25.get_scores(tokenized_query)

    top_indices = np.argsort(scores)[-k:]

    return [documents[i] for i in top_indices]

def retrieve_faiss(query, k=5):

    query_vector = embedding_model.encode([query])

    distances, indices = index.search(np.array(query_vector), k)

    return [documents[i] for i in indices[0]]

generator = pipeline(
    "text-generation",
    model="gpt2",
    max_length=200
)

def generate_rag_answer(query, retrieved_docs):

    context = "\n".join(retrieved_docs[:3])   # limit context

    prompt = f"""
Use the following product reviews to answer the user query.

Reviews:
{context}

User Query:
{query}

Recommendation:
"""

    result = generator(
        prompt,
        max_new_tokens=100,
        do_sample=True,
        temperature=0.7
    )

    return result[0]["generated_text"]

query = "good book for learning machine learning"

bm25_docs = retrieve_bm25(query)
faiss_docs = retrieve_faiss(query)

print("BM25 RAG Answer:")
print(generate_rag_answer(query, bm25_docs))

print("\nFAISS RAG Answer:")
print(generate_rag_answer(query, faiss_docs))

queries = [
    "moisturizer for dry skin",
    "long lasting lipstick",
    "face cleanser for sensitive skin",
    "anti aging cream"
]

ground_truth = {
    "moisturizer for dry skin": ["moisturizer", "dry", "hydrating"],
    "long lasting lipstick": ["lipstick", "long-lasting"],
    "face cleanser for sensitive skin": ["cleanser", "sensitive"],
    "anti aging cream": ["anti-aging", "wrinkle", "cream"]
}

def precision_at_k(retrieved_docs, relevant_keywords, k=5):
    relevant_count = 0

    for doc in retrieved_docs[:k]:
        if any(word in doc.lower() for word in relevant_keywords):
            relevant_count += 1

    return relevant_count / k

def recall_at_k(retrieved_docs, relevant_keywords):
    relevant_count = 0

    for doc in retrieved_docs:
        if any(word in doc.lower() for word in relevant_keywords):
            relevant_count += 1

    return relevant_count / len(relevant_keywords)

def retrieve_bm25(query, k=5):
    scores = bm25.get_scores(query.split())
    top_k_idx = np.argsort(scores)[::-1][:k]
    return [documents[i] for i in top_k_idx]

def retrieve_faiss(query, k=5):
    query_vec = model.encode([query])
    distances, indices = index.search(query_vec, k)
    return [documents[i] for i in indices[0]]

def precision_at_k(retrieved_docs, keywords, k=5):
    relevant = 0
    for doc in retrieved_docs[:k]:
        if any(word in doc.lower() for word in keywords):
            relevant += 1
    return relevant / k

results = []

for query in queries:

    bm25_docs = retrieve_bm25(query, 5)
    faiss_docs = retrieve_faiss(query, 5)

    keywords = ground_truth[query]

    bm25_p = precision_at_k(bm25_docs, keywords)
    faiss_p = precision_at_k(faiss_docs, keywords)

    bm25_r = recall_at_k(bm25_docs, keywords)
    faiss_r = recall_at_k(faiss_docs, keywords)

    results.append({
        "query": query,
        "bm25_precision": bm25_p,
        "faiss_precision": faiss_p,
        "bm25_recall": bm25_r,
        "faiss_recall": faiss_r
    })

import pandas as pd

df_results = pd.DataFrame(results)
print(df_results)

df_results.plot(x="query", y=["bm25_precision", "faiss_precision"], kind="bar")
plt.title("Precision Comparison")
plt.show()

import nbformat

nb = nbformat.read("/Copy_of_Thesis_code.ipynb", as_version=4)

# Remove widget metadata
if "widgets" in nb["metadata"]:
    del nb["metadata"]["widgets"]

nbformat.write(nb, "clean_notebook.ipynb")